### PR TITLE
Update data.json

### PR DESCRIPTION
**Pull request by Daksheshapkare**
#8  please look after this pr and merge it under hacktoberfest 
If any changes please comment don't close as invalid or spam please

### CODE REVIEW

**Comment by vijayyprajapati** [comment]
Your PR does not follow contribution guidelines.
You need to provide all the links as others have provided.

**Comment by vijayyprajapati** [comment]
Resolve this and raise a new PR.

**Review by Daksheshapkare — COMMENTED** [review]
@vijayyprajapati 
I have done the changes that you have asked 
Please refer it and comment me if any changes

**Comment by vijayyprajapati** [comment]
Good job @Daksheshapkare

**Pull request merged**
