### PR TITLE
adding redirecting arrow

### LINKED ISSUE #80: Change the home link  to slide back to previous page
Currently to go from user detail page to home page we have to click on home . How about adding an arrow like the one shown below.

### PR DESCRIPTION
**Pull request by Snehil0603**
# FIXES #80 
Redirecting arrow has been added

### CODE REVIEW

**Comment by Snehil0603** [comment]
> The alignment of the user data is little shifted can you fix this issue? And make it mobile responsive as well.

ok , I will do it

**Comment by vijayyprajapati** [comment]
you have done a good job can you decrease the size of the arrow button in web view?

**Comment by Snehil0603** [comment]
@vijayyprajapati  I have reshaped the button. Kindly check the PR now. Also can you please add hackotober tag.

**Comment by vijayyprajapati** [comment]
Great @Snehil0603

**Pull request merged**
