### PR TITLE
improve share bookmark index and detail page

### PR DESCRIPTION
**Pull request by Laikokwui**
- added a button to back to home page in detail.html
- improve styling page for detail html

color palette used:
#090909 #4B5043 #9BC4BC #D3FFE9 #8DDBE0

### CODE REVIEW

**Comment by vijayyprajapati** [comment]
You have done great job.
you just need to fix the problem of hovering on the social media buttons and on the links.
Make the home button more eye-catching

**Comment by Laikokwui** [comment]
@vijayyprajapati done. and i added a footer. just a template using bootstrap

**Comment by vijayyprajapati** [comment]
We don't need a footer for now so remove that and raise a PR again.

**Comment by Laikokwui** [comment]
@vijayyprajapati alright as you wish :)

**Comment by vijayyprajapati** [comment]
Excellent @Laikokwui 
Keep contributing.

**Pull request merged**
