### PR TITLE
Backend integrated with frontend

### PR DESCRIPTION
**Pull request by deepakgohil009**
Issue #141 

@vijayyprajapati 

I had integrated the backend with frontend. From now onward the way of adding data is different. Please have a look on that before merging.

From now if anyone wants to add thier bookmark data then he/she have to run following command in terminal :
```
curl -X POST https://bookmark-vqbz.onrender.com/ \
   -H 'Content-Type: application/json' \
   -d '{
    "name": "your name here",
    "username": "your_unique_username_here",
    "bio": "your bio here",
    "links": [
      "your first bookmark link",
      "your second bookmark link",
      "your third bookmark link",
      "your fourth bookmark link",
      "your fifth bookmark link"
    ],
    "social": {
        "twitter": "your twitter/other handle here",
        "linkedin": "your linkedin/other handle here"
    }
}'
```

We can create frontend page for this to add data directly through website instead of running this command.

### CODE REVIEW

**Comment by deepakgohil009** [comment]
@vijayyprajapati have a look on README.md before merging. And do let me know if changes are needed to be made.

**Comment by deepakgohil009** [comment]
@vijayyprajapati apart from this now as backend is being added to this app. I had also implemented more functionalities like updating data, adding more links and deleting data etc. So for this functionalities backend is being already made. We need some more pages in frontend so can If you don't mind Can I raise more issues so that other contributors can contribute to this issues.

**Comment by vijayyprajapati** [comment]
Hey @deepakgohil009 
I am reviewing your code.
If I will have doubts then I will contact you.

**Comment by deepakgohil009** [comment]
Sure, you can find working site on https://deploy-preview-156--share-your-bookmarks.netlify.app/

**Comment by deepakgohil009** [comment]
@vijayyprajapati backend is being removed from main branch. So now there is merge conflict so should I make a new PR to re-add the backend to codebase ?

**Comment by vijayyprajapati** [comment]
@deepakgohil009 raise a new PR.

**Pull request closed without merging**
