### PR TITLE
Design of Community Guideline page

### PR DESCRIPTION
**Pull request by bhoomikhurana**

### CODE REVIEW

**Comment by vijayyprajapati** [comment]
Hey @bhoomikhurana. I am very impressed with your work. You have done a great job.
It can be better if you could reduce the width of the container. 
One more thing I wanted to know that, In imgs folder why have you add .DS_Store file?

**Comment by bhoomikhurana** [comment]
Hii,yes sure sending the PR again after changes.Actually I didn’t add the
.DS_Store file,neither it is showing to me.It probably got added by mac.You
can place it in .gitignore folder

**Comment by vijayyprajapati** [comment]
Hey @bhoomikhurana 
You have done a great job. I appreciate your work.
Keep contributing.

**Comment by vijayyprajapati** [comment]
You can also add your profile and raise a new PR.

**Pull request merged**
