### PR TITLE
Improved the hover effect on bookmark links in details page

### PR DESCRIPTION
**Pull request by vikash485**
Solved issue #75

### CODE REVIEW

**Comment by vikash485** [comment]
Please check this @vijayyprajapati. Thanks

**Comment by vijayyprajapati** [comment]
When we hover over links the list number is not visible. Can you fix that also and then make a new PR?

**Comment by vikash485** [comment]
> When we hover over links the list number is not visible. Can you fix that also and then make a new PR?

Sure, will update this pr in a bit

**Comment by vikash485** [comment]
Hey @vijayyprajapati , I made the list number visible, and the website looks more neat show. Please check

**Comment by vijayyprajapati** [comment]
Hey @vikash485 
You did a great job but the idea of showing the list number in the box is not good. The number on the list item should be shown outside of the boxes. you just need to fix the color of the list on hover also.
Try to fix that.

**Comment by vikash485** [comment]
> Hey @vikash485 You did a great job but the idea of showing the list number in the box is not good. The number on the list item should be shown outside of the boxes. you just need to fix the color of the list on hover also. Try to fix that.

do you have any preference for the color, or any color that looks good will do?

**Comment by vikash485** [comment]
Please check now @vijayyprajapati , I have kept the original color of the link, it feels good to me.

**Comment by vikash485** [comment]
I have fixed all the issues now, please verify and merge @vijayyprajapati. Thanks

**Comment by vikash485** [comment]
> Great @vikash485 Is it possible that when we hover over the links, the link text color becomes black but the list number color remains the same.

Okay trying that as well

**Comment by vikash485** [comment]
Done that as well, please check now @vijayyprajapati

**Comment by vijayyprajapati** [comment]
Excellent @vikash485 
I hope you learned something new.
Keep contributing and sharpening your skills.

**Pull request merged**
