### PR TITLE
Hacktoberfest 2022 - Added myself

### PR DESCRIPTION
**Pull request by nightshadetvn**

### CODE REVIEW

**Comment by vijayyprajapati** [comment]
Hey @nightshadetvn 
Your PR does not follow the contribution guidelines.
You need to provide at least 5 bookmark links and LinkedIn profile link also.

**Comment by vijayyprajapati** [comment]
Hey @nightshadetvn 
You need to follow the schema that others have followed.
You just need to copy one person and then change the data only.

**Comment by nightshadetvn** [comment]
Sup @vijayyprajapati could we redeploy it now?

**Comment by vijayyprajapati** [comment]
Fork the repo again and try to contribute.

**Pull request closed without merging**
